# AdvancedFreezeStick Plugin Configuration
max_uses: 10
stick_name: "&bFreezing Stick"
stick_lore:
  - "&7Right-click to freeze a player!"
  - "&7Remaining Uses: &e%d%/%d%"
custom_model_data: 123
cooldown: 5
freezing_time: 5

